### ISSUE TITLE
segv fault

### ISSUE THREAD

**Issue by red55** [red55/bgp-dns#23]
https://github.com/red55/bgp-dns/blob/68d437507ad20fd10a164919a0ae5366619018f1/internal/dns/responder.go#L34

**Comment by red55** [comment]
```
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xb995f6]
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]: goroutine 31 [running]:
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]: github.com/red55/bgp-dns/internal/dns.respond({0xee4fa0, 0xc0003cfc00}, 0xc0003ba480)
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]:         /home/runner/work/bgp-dns/bgp-dns/internal/dns/responder.go:34 +0x2f6
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]: github.com/miekg/dns.HandlerFunc.ServeDNS(0xc000088a20?, {0xee4fa0?, 0xc0003cfc00?}, 0x1?)
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]:         /home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:37 +0x29
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]: github.com/miekg/dns.(*ServeMux).ServeDNS(0xc000470200?, {0xee4fa0?, 0xc0003cfc00?}, 0xc0003ba480?)
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]:         /home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/serve_mux.go:103 +0x6e
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]: github.com/miekg/dns.(*Server).serveDNS(0xc00024d200, {0xc000470200, 0x26, 0x200}, 0xc0003cfc00)
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]:         /home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:663 +0x42a
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]: github.com/miekg/dns.(*Server).serveUDPPacket(0xc00024d200, 0xc000201a90, {0xc000470200, 0x26, 0x200}, {0xee2300, 0xc00006a8d8}, 0xc00039eb40, {0x0, 0x0})
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]:         /home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:607 +0x1a5
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]: created by github.com/miekg/dns.(*Server).serveUDP in goroutine 45
Aug 17 08:43:57 14700.example.com bgp-dnsd[910488]:         /home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:537 +0x405
Aug 17 08:43:57 14700.example.com systemd[1]: bgp-dnsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 17 08:43:57 14700.example.com systemd[1]: bgp-dnsd.service: Failed with result 'exit-code'.
```

**Comment by red55** [comment]
V2 is not affected
